### ISSUE TITLE
Please update this!

### ISSUE THREAD

**Issue by Slowstone72** [PrismarineJS/mineflayer-scaffold#9]
mineflayer-scaffold is a great idea, but I wish it would be updated so that it actually works correctly. Still getting the same error as #7
First, it kind of works, and it builds upwards, but that's it, and then 90% of the time there's an "interrupt" error. So please update it when you can, I think it could be really useful!

**Comment by FrostBird347** [comment]
I also get the same error as [#7](https://github.com/PrismarineJS/mineflayer-scaffold/issues/7) 
UNFINISHED, JUST CHECKING THE LINK

**Comment by miguel-acevedo** [comment]
Did anyone ever find a fix?
